dashboard/urls.py
from django.urls import path
from .views import *
from .api import *

app_name = 'dashboard'

urlpatterns = [
    path('', index, name='index'),
    path('inbox', inbox, name='inbox'),
    path('inbox/compose', inbox_create, name='inbox_new'),
    path('inbox/sent', sent_inbox, name='sent_inbox'),
    path('inbox/<int:inbox_id>', inbox_content, name='inbox_content'),
    path('logout', signout, name='signout'),

    path('api/attachment/upload', upload_attachment, name='upload_attach'),
    path('api/attachment/delete', delete_attachment, name='delete_attach'),
    path('api/inbox/fetch', get_user_inbox, name='fetch_inbox'),
    path('api/inbox/delete', delete_user_inbox, name='delete_inbox'),
    path('api/inbox/sent', get_user_sent_inbox, name='fetch_sent_inbox'),
    path('api/notifications/fetch', get_notifications, name='fetch_notifications'),

    path('groups', groups, name='groups'),
    path('groups/create', group_add, name='group_add'),
    path('groups/edit/<int:groupId>', group_edit, name='group_edit'),
    path('groups/delete/<int:groupId>', group_delete, name='group_delete'),

    path('students/', students, name='students'),
    path('students/<int:student_id>', students, name='students'),
    path('students/delete/<int:student_id>', students_delete, name='students_delete'),

    path('staffs/', staffs, name='staffs'),
    path('staffs/<int:staff_id>', staffs, name='staffs'),
    path('staffs/delete/<int:staff_id>', staffs_delete, name='staffs_delete'),

    path('profile/', profile, name='profile'),
]

home/urls.py
from django.urls import path, include
from .views import *
from dashboard.views import (signin, register_student, register_success, register_staff)

app_name = 'home'

urlpatterns = [
    path('', index, name='index'),
    path('register/student', register_student, name='register_student'),
    path('register/staff', register_staff, name='register_staff'),
    path('register/success/<int:userid>', register_success, name='register_success'),
    path('login', signin, name='login'),
    path('dashboard/', include('dashboard.urls'))
]

spas/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('', include('home.urls')),
    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

home/models.py
from django.db import models
from django.contrib.auth.models import PermissionsMixin
from django.contrib.auth.base_user import AbstractBaseUser
from django.utils.translation import ugettext_lazy as _
# from django.db.models.signals import post_save
# from django.dispatch import receiver
# from django.conf import settings
from .managers import UserManager


def user_directory_path(instance, filename):
    # file will be uploaded to media/users/avatars/user_<email>/<filename>
    return 'users/avatars/{0}/{1}'.format(instance.email, filename)


class User(AbstractBaseUser, PermissionsMixin):
    email = models.EmailField(_('email address'), unique=True)
    name = models.CharField(_('name'), max_length=30)
    phone = models.CharField(_('phone'), max_length=20)
    address = models.CharField(_('address'), max_length=50)
    is_active = models.BooleanField(_('is active'), default=False)
    is_staff = models.BooleanField(default=False)
    is_superuser = models.BooleanField(_('is super'), default=False)
    last_login = models.DateTimeField(blank=True, null=True)
    created_at = models.DateTimeField(_('date created'), auto_now_add=True)
    updated_at = models.DateTimeField(_('date updated'), auto_now_add=True)
    avatar = models.ImageField(upload_to=user_directory_path, null=True, blank=True)

    objects = UserManager()

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['name', 'phone']

    class Meta:
        verbose_name = _('user')
        verbose_name_plural = _('users')


class StudentProfile(models.Model):
    student = models.ForeignKey(User, on_delete=models.CASCADE)
    department = models.CharField(_('department'), max_length=20)
    faculty = models.CharField(_('faculty'), max_length=20)
    level = models.IntegerField(_('level'), default=100)
    reg_no = models.CharField(_('registration number'), max_length=20, unique=True)


ROLE_CHOICES = (
    ('ADMIN', 'Admin'),
    ('DEFAULT', 'Default')
)


class StaffProfile(models.Model):
    staff = models.ForeignKey(User, on_delete=models.CASCADE)
    role = models.CharField(max_length=100, choices=ROLE_CHOICES, blank=True)
    staffId = models.CharField(_('Staff ID'), max_length=20, unique=True)

#
# @receiver(post_save, sender=settings.AUTH_USER_MODEL)
# def create_user_log(sender, instance, created, **kwargs):
#     if created:
#         if instance.is_staff:
#             StaffProfile.objects.create(
#                 staff=instance,
#                 role='TYPE_A',
#                 message='User Created Successfully',
#             ).save()

dashboard/views.py
from django.shortcuts import render, redirect
from home.models import User, StudentProfile, StaffProfile
from .models import (Group, Message, MessageState, Attachment, MessageThread)
from django.db import IntegrityError
from django.contrib.auth import (authenticate, login, logout)
from django.contrib.auth.decorators import login_required
from .forms import (PasswordChangeForm, CreateGroupForm, AvatarUpdateForm, UserUpdateForm, StaffProfileUpdateForm, StudentProfileUpdateForm)
from django.contrib.admin.views.decorators import staff_member_required
import datetime
import pytz


@login_required
def index(request):
    response = {
        'inbox': {
            'count': 0,
            'read': 0,
            'unread': 0,
            'sent': 0
        },
        'sms': {
            'count': 0,
            'threads': 0,
            'groups': 0
        },
        'users': {
            'count': 0,
            'staffs': 0,
            'students': 0,
            'admins': 0
        }
    }
    all_sms = Message.objects.all()
    all_sms_threads = MessageThread.objects.all()
    all_sms_groups = Group.objects.all()
    users = User.objects.all()

    user_inbox = all_sms.filter(receivers=request.user)
    user_msg_states = [x.get_message_state(request.user) for x in user_inbox]
    user_read_msg_states = list(filter(lambda x: x is True, user_msg_states))
    user_unread_msg_states = len(user_msg_states) - len(user_read_msg_states)
    user_sent_inbox = all_sms.filter(sender=request.user)

    response['inbox']['count'] = user_inbox.count()
    response['inbox']['sent'] = user_sent_inbox.count()
    if len(user_msg_states) > 0:
        response['inbox']['read'] = len(user_read_msg_states)
        response['inbox']['unread'] = user_unread_msg_states

    response['sms']['count'] = all_sms.count()
    response['sms']['threads'] = all_sms_threads.count()
    response['sms']['groups'] = all_sms_groups.count()

    response['users']['count'] = users.count()
    response['users']['staffs'] = users.filter(is_staff=True).count()
    response['users']['students'] = users.filter(is_staff=False).count()
    response['users']['admins'] = StaffProfile.objects.filter(role='ADMIN').count()
    # update level
    if not request.user.is_staff:
        registered_on = request.user.created_at
        now = datetime.datetime.utcnow().replace(tzinfo=pytz.UTC)
        difference = now - registered_on
        year = int(difference.total_seconds()/31540000.0010112)*100
        level = 100 if (year*100) == 0 else (year*100)
        student_profile = StudentProfile.objects.get(student=request.user.id)
        student_profile.level = level
        student_profile.save()
    return render(request, 'dashboard/index.html', response)


def register_student(request):
    response = {
        "error": False
    }
    if request.method == 'POST':
        try:
            superadmin = User.objects.get(pk=1)
            if not (superadmin.is_superuser and superadmin.is_staff):
                raise User.DoesNotExist
        except User.DoesNotExist:
            response['error'] = True
            response['message'] = "Please create a superuser for this platform"
        else:
            try:
                user = User.objects.create(
                    email=request.POST['email'],
                    name=request.POST['name'],
                    phone=request.POST['phone'],
                    address=request.POST['address'],
                    avatar=request.FILES['avatar'],
                )
                user.set_password(request.POST['password'])
                user.save()
                student_profile = StudentProfile.objects.create(
                    student=user,
                    department=request.POST['department'],
                    faculty=request.POST['faculty'],
                    level=request.POST['level'],
                    reg_no=request.POST['regNo']
                )

                # Automatically add categorization
                # department
                try:
                    tmp_department = Group.objects.get(title=request.POST['department'].upper())
                    tmp_department.members.add(user)
                    tmp_department.save()
                except Group.DoesNotExist:
                    new_group = Group()
                    new_group.context = 'DEPARTMENT'
                    new_group.default = True
                    new_group.title = request.POST['department'].upper()
                    new_group.created_by = superadmin
                    new_group.save()
                    new_group.members.add(user)
                    new_group.save()
                # faculty
                try:
                    tmp_faculty = Group.objects.get(title=request.POST['faculty'].upper())
                    tmp_faculty.members.add(user)
                    tmp_faculty.save()
                except Group.DoesNotExist:
                    new_group = Group()
                    new_group.title = request.POST['faculty'].upper()
                    new_group.context = 'FACULTY'
                    new_group.default = True
                    new_group.created_by = superadmin
                    new_group.save()
                    new_group.members.add(user)
                    new_group.save()
                # level
                try:
                    tmp_level = Group.objects.get(title=request.POST['level'])
                    tmp_level.members.add(user)
                    tmp_level.save()
                except Group.DoesNotExist:
                    new_group = Group()
                    new_group.context = 'LEVEL'
                    new_group.default = True
                    new_group.title = request.POST['level']
                    new_group.created_by = superadmin
                    new_group.save()
                    new_group.members.add(user)
                    new_group.save()

            except IntegrityError:
                response['error'] = True
                response['message'] = "Duplicate Registration Number Found"
            else:
                return redirect('home:register_success', user.id)
    return render(request, 'dashboard/auth/registerStudent.html', response)


def register_staff(request):
    response = {
        "error": False
    }
    if request.method == 'POST':
        try:
            admins = User.objects.filter(is_staff=True)
            user = User.objects.create(
                email=request.POST['email'],
                name=request.POST['name'],
                phone=request.POST['phone'],
                address=request.POST['address'],
                avatar=request.FILES['avatar'],
                is_staff=True
            )
            if admins.count() == 0:
                user.is_active = True
            user.set_password(request.POST['password'])
            user.save()
            staff_profile = StaffProfile.objects.create(
                staff=user,
                role=request.POST['role'],
                staffId=request.POST['staffId'],
            )
        except IntegrityError:
            response['error'] = True
            response['message'] = "Duplicate Staff ID Found"
        else:
            return redirect('home:register_success', user.id)
    return render(request, 'dashboard/auth/registerStaff.html', response)


def register_success(request, userid):
    try:
        user = User.objects.get(pk=userid)
    except User.DoesNotExist:
        return redirect('home:index')
    else:
        return render(request, 'dashboard/registerSuccess.html')


def signin(request):
    response = {
        "error": False
    }
    if request.method == 'POST':
        try:
            next_url = request.POST['next']
            user = User.objects.get(email=request.POST['email'])
            if not user.is_active:
                raise ValueError
            user = authenticate(request, email=request.POST['email'], password=request.POST['password'])
            if user is not None:
                login(request, user)
                if next_url:
                    return redirect(next_url)
                return redirect('home:dashboard:index')
            else:
                raise User.DoesNotExist
        except User.DoesNotExist:
            response['error'] = True
            response['message'] = "Invalid Email or Password"
        except ValueError:
            response['error'] = True
            response['message'] = "You have not been activated. Kindly contact the admin."
    return render(request, 'dashboard/auth/login.html', response)


def signout(request):
    logout(request)
    return redirect('home:login')


@login_required
def inbox(request):
    group_id = request.GET.get('groupId')
    user_message_groups = Group.objects.filter(members=request.user)
    if not group_id:
        group_id = ''
    return render(request, 'dashboard/inbox/inbox.html', {
        'grouped': (lambda x: True if len(x) > 0 else False)(group_id),
        'message_groups': user_message_groups
    })


@login_required
def sent_inbox(request):
    user_message_groups = Group.objects.filter(members=request.user)
    return render(request, 'dashboard/inbox/inboxSent.html', {
        'message_groups': user_message_groups
    })


@login_required
def inbox_create(request):
    messages = Message.objects.filter(receivers=request.user)
    user_message_groups = Group.objects.filter(members=request.user)
    if request.method == 'POST':
        send_to = request.POST['to'].split(',')    # [email,email,email]
        group_id = request.POST['group']   # group id
        subject = request.POST['subject']
        content = request.POST['content']
        send_to_context = request.POST['sendToContext']     # email or group
        attachment_ids = request.POST['attachments'].split(',')

        new_message = Message(content=content, subject=subject, sender=request.user)
        new_message.save()

dashboard/templates/dashboard/user/staff.html
{% extends 'dashboard/base.html' %}
{% block title %} Staffs{% endblock %}
{% block pageName %}Manage Staffs{% endblock %}

{% block content %}
    <div class="components-preview mx-auto px-3 pt-5">
        <div class="nk-block nk-block-lg">
            <div class="nk-block-head">
                <div class="nk-block-head-content">
                    <h4 class="nk-block-title">
                        All Staffs
                    </h4>
                    <div class="nk-block-des">
                        <p>Actions can only be carried by roles of <span class="tb-status text-success">recognized</span> priviledges</p>
                    </div>
                </div>
            </div>
            <div class="card card-preview">
                <div class="card-inner">
                    {% if staffs %}
                        <table class="datatable-init nk-tb-list nk-tb-ulist" data-auto-responsive="false">
                            <thead>
                            <tr class="nk-tb-item nk-tb-head">
                                <th class="nk-tb-col"><span class="sub-text">Staff</span></th>
                                <th class="nk-tb-col tb-col-mb"><span class="sub-text">Staff ID</span></th>
                                <th class="nk-tb-col tb-col-mb"><span class="sub-text">Role</span></th>
                                <th class="nk-tb-col tb-col-md"><span class="sub-text">Phone</span></th>
                                <th class="nk-tb-col tb-col-lg"><span class="sub-text">Address</span></th>
                                <th class="nk-tb-col tb-col-md"><span class="sub-text">Status</span></th>
                                <th class="nk-tb-col nk-tb-col-tools text-right"></th>
                            </tr>
                            </thead>
                            <tbody>
                            {% for staff in staffs %}
                                <tr class="nk-tb-item">
                                    <td class="nk-tb-col">
                                        <div class="user-card">
                                            <div class="user-avatar bg-dim-primary d-none d-sm-flex">
                                                {% if staff.avatar %}
                                                    <div class="user-avatar user-avatar-custom">
                                                        <img class="avatar" src="{{ staff.avatar.url }}" alt="user image">
                                                    </div>
                                                {% else %}
                                                    <span>{{ staff.name|truncatechars:3 }}</span>
                                                {% endif %}
                                            </div>
                                            <div class="user-info">
                                            <span class="tb-lead">
                                                {{ staff.name }}
                                            </span>
                                                <span>{{ staff.email }}</span>
                                            </div>
                                        </div>
                                    </td>
                                    <td class="nk-tb-col tb-col-mb">
                                        <span>{{ staff.staffprofile_set.first.staffId }}</span>
                                    </td>
                                    <td class="nk-tb-col tb-col-mb">
                                        <span>{{ staff.staffprofile_set.first.role }}</span>
                                    </td>
                                    <td class="nk-tb-col tb-col-md"><span>{{ staff.phone }}</span></td>
                                    <td class="nk-tb-col tb-col-lg"><span>{{ staff.address }}</span></td>
                                    <td class="nk-tb-col tb-col-md">
                                        {% if staff.is_active %}
                                            <span class="tb-status text-success">active</span>
                                        {% else %}
                                            <span class="tb-status text-warning">inactive</span>
                                        {% endif %}
                                    </td>
                                    <td class="nk-tb-col nk-tb-col-tools">
                                        <ul class="nk-tb-actions gx-1">
                                            {% if request.user.is_superuser %}
                                                <li>
                                                    <div class="dropdown">
                                                        <a href="javascript:void(0)" class="dropdown-toggle btn btn-icon btn-trigger" data-toggle="dropdown">
                                                            <em class="icon ni ni-more-h"></em>
                                                        </a>
                                                        <div class="dropdown-menu dropdown-menu-right">
                                                            <ul class="link-list-opt no-bdr">
                                                                {% if staff.is_active %}
                                                                    <li>
                                                                        <a href="{% url 'home:dashboard:staffs' staff.id %}">
                                                                            <em class="icon ni ni-alert text-warning"></em><span>Mark as inactive</span>
                                                                        </a>
                                                                    </li>
                                                                {% else %}
                                                                    <li>
                                                                        <a href="{% url 'home:dashboard:staffs' staff.id %}">
                                                                            <em class="icon ni ni-check-circle text-success"></em>
                                                                            <span>Mark as active</span>
                                                                        </a>
                                                                    </li>
                                                                {% endif %}
                                                                <li>
                                                                    <a class="spas-usr-del" href="{% url 'home:dashboard:staffs_delete' staff.id %}">
                                                                        <em class="icon ni ni-delete-fill"></em><span>Delete</span>
                                                                    </a>
                                                                </li>
                                                                <li class="divider"></li>
                                                                <li>
                                                                    <a href="javascript:void(0)">
                                                                        <small class="icon ni ni-shield-star"></small>
                                                                        <small>SPAS V1.0</small>
                                                                    </a>
                                                                </li>
                                                            </ul>
                                                        </div>
                                                    </div>
                                                </li>
                                            {% endif %}
                                        </ul>
                                    </td>
                                </tr>
                            {% endfor %}
                            </tbody>
                        </table>
                    {% else %}
                        <div class="d-flex justify-content-center">
                            <p>Empty Staffs History</p>
                        </div>
                    {% endif %}
                </div>
            </div>
        </div>
    </div>
{% endblock %}

{% block script %}
    <script>
        $('.spas-usr-del').on('click', function(event){
            event.preventDefault();
            const status = confirm("Continue with this operation?");
            if(status){
                window.location.href = $(this).attr('href')
            }
        })
    </script>
{% endblock %}